services:
  - type: web
    name: prohealium-api
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: ProHealium RxPMS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://prohealium.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-shiny-paper-ayyttb1n-pooler.c-5.us-east-2.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_lgVh1XwSEv8J
      - key: DB_SSLMODE
        value: require
      - key: DB_NEON_ENDPOINT
        value: ep-shiny-paper-ayyttb1n
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
